name: Security

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  security-events: write # Required for SARIF uploads
  actions: read
  contents: read

jobs:
  osv-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@8dded7155905cd666190a12dc9997000e58d163d # v2
        with:
          scan-args: --recursive --format sarif --output osv-results.sarif ./app

      - name: Upload OSV Scanner report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: osv-results.sarif

  semgrep-scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep analysis
        run: semgrep scan --config=p/java --sarif -o semgrep-results.sarif

      - name: Upload Semgrep report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
